### PR TITLE
solve the issue #3

### PR DESCRIPTION
**Pull request by Sucran**
Hi @Ahmkel , I solved my issue on my own.
The issue is similar to a issue on stackoverflow [https://stackoverflow.com/questions/1713038/super-fails-with-error-typeerror-argument-1-must-be-type-not-classobj](url), you can check the answer and the code.

### CODE REVIEW

**Comment by Sucran** [comment]
the BaseModel and BaseTrain have the same issue

**Comment by Ahmkel** [comment]
Hi, thanks for pointing this out.
I forgot to mention in the readme that the template was developed mainly for python 3.x,, I haven't tried to run it with python 2.x so I didn't see the problem.

**Comment by Sucran** [comment]
May be you can add a Requirements section on README like this:

### Requirements
This code requires Keras 2.*, Tensorflow 1.3.\* or higher version, Python 3.*  as well as the following python libraries:
- bunch
- ....

**Comment by Ahmkel** [comment]
Thanks for contributing! :+1:

**Pull request merged**
